name: 'Pull request checks'

on:
  pull_request:


env:
  TF_LOG: INFO
  AWS_DEFAULT_REGION: "eu-central-1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test and build js
        uses: ejfschmittel/actions/npm_test_and_build@master
        with:
          artifact_name: ${{ github.event.repository.name }}-${{ github.event.after }}
          artifact_path: dist
  infra:
    name: "Plan terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the terraform directory.
        working-directory: ./terraform

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform format
        id: fmt
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: terraform plan -input=false