name: 'Pull request checks'

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node_version: 16.18
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build